# Generated by Django 6.1.1 on 2026-09-27 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('Coffee', 'Coffee'), ('Tea', 'Tea'), ('Cold Drinks', 'Cold Drinks'), ('Snacks', 'Snacks'), ('Desserts', 'Desserts')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.URLField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
